### ISSUE TITLE
@template path shortcut

### ISSUE THREAD

**Issue by yissachar** [nippur72/RiotTS#21]
When using the template annotation to refer to an external HTML file, I assume the vast majority of situations will refer to a file with the same name and at the same folder level, but with an HTML extension instead of TS. For example:
- my-element.ts
- my-element.html

Since this is the case, it seems that the user shouldn't have to type out the full path each time. Some type  of shortcut would be nice here.

Perhaps if a `Riot.Element` is annotated with a blank template annotation it will look for an HTML file with the same name within that folder?

For instance if we had `my-element.ts` with the following code:

```
@template()
class MyElement extends Riot.Element {
    // ...
}
```

RiotTS would attempt to find `my-element.html` within that folder and use that as the template for `MyElement`.

I think this would make it a bit easier to create new elements, as well as making it easier to refactor.

**Comment by nippur72** [comment]
it makes sense, but the problem is that you don't have access to the "filename" information at runtime (or even at compile time as far as I know), so the `@template` decorator can't figure out what file is being called from. 

An alternative I was thinking about recently would be using tag names in place of path, e.g.:

```
@template("hello-world")
class HelloWorldTag extends Riot.Element {}
```

but that could work only when precompiled tags are turned on (because in that case you have a list of all custom tags in the application). If precompiled tags are off, there is still no clue on where to physically look for the tag.

**Comment by yissachar** [comment]
Ah right, I am using precompiled tags, and forgot that this would have to take runtime tags into effect as well.

**Comment by nippur72** [comment]
@yissachar I've updated the grunt plugin to accept an option `indexByTagName`, so that the precompiled file is indexed by tag name instead of file path.

This means you can specify only the tagname in the `@template()` decorator instead of path. It's nice because it's shorter and your are free to move .html files without worries, but of course this breaks the no-precompiled tags scenario.

**Comment by yissachar** [comment]
Excellent, this is much nicer! I also like how the need to register was removed in the last release. Good stuff :+1:
