### ISSUE TITLE
Template Syntax highlight

### ISSUE THREAD

**Issue by daslicht** [nippur72/RiotTS#26]
Hi,
when using the @template() decorator you wont get syntax highlight or codecompletion in any ide.

Is there a way ?

Or is there a way to use inline templates like in 'normal' riot?

**Comment by nippur72** [comment]
if you use the inline string syntax, there can't be any syntax highlight, because for the compiler it's just a string. You must split it into a separate file (which gives you also the benefit of pre-compilation).

Anyway, TypeScript folks are working on language extensibility (see [https://github.com/Microsoft/TypeScript/issues/6508](https://github.com/Microsoft/TypeScript/issues/6508)) so perhaps in the future it will be possible to mix TypeScript code with foreign code like HTML, SQL etc.

**Comment by daslicht** [comment]
Sounds great! Thank you !
