### ISSUE TITLE
riot-ts.js

### ISSUE THREAD

**Issue by daslicht** [nippur72/RiotTS#27]
What is riot-ts.js responsible for ? 

If you have created an app in RiotTS and transpiled everything to to TS could we drop riot-ts.js ?

**Comment by nippur72** [comment]
The main problem is that `riot` itself is not ES6 friendly, it's not written around the concept of "classes": a tag in riot is a "closure function" instead of being an ES6 class.

What RiotTS does is making such closure function look like an ES6 class that you can extend (`Riot.Tag`). Also it provides the `@template` decorator that binds (at runtime) the template to the tag prototype. 

There was a discussion about that some time ago on the riot's repo, see https://github.com/riot/riot/issues/1451

**Comment by daslicht** [comment]
but that way there is a anytime that wrapper needed ? Isn't there a way to compile it to es5 ?
What about performance degration ?
